// <auto-generated />
namespace P2659902___Library_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PaymentTypeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PaymentTypeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202405131236287_PaymentTypeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
